name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for using F@antom, please make sure your issue is not a duplicate'
        pr-message: 'Thanks for contributing to F@ntom, please make sure you format your code and, thanks once again!'
